<h1>SciPy<h1>
<p>SciPy is a python library that is built on NumPy and can be integrated with other data science libraries like pandas and matplotlib. It can perform many mathematical operations that include modules for linear algebra, optimization, integration, interpolation, special functions, FFT, signal and image processing, ODE solvers, etc. <p>

<h2>Installing SciPy<h2>

In [1]:
!pip install scipy

<h2>Importing Scipy<h2>

In [2]:
import numpy as np
from scipy import linalg

<h2>Creating a matrix<h2>

In [3]:
A = np.array([[1,2],[3,4]])

<h2>Matrix Inverse<h2>

In [4]:
linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

<h2>Lower Triangular and Upper Traingular Matrix

In [5]:
linalg.lu(A)

(array([[0., 1.],
        [1., 0.]]),
 array([[1.        , 0.        ],
        [0.33333333, 1.        ]]),
 array([[3.        , 4.        ],
        [0.        , 0.66666667]]))

<h2>Creating an Orthogonal Matrix<h2>

In [6]:
linalg.orth(A)

array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]])