<h1>Tiny NumPy<h1>
<p>Tiny NumPy is a python library that is similar to Numpy but has limited functionality. One can calculate matrices and vectors using Tiny Numpy. However, like tiny array, it is faster than NumPy but not suitable for large arrays. </p>

<h2>Installing Tiny NumPy<h2>

In [1]:
!pip install tinynumpy

  Preparing metadata (setup.py) ... done
  Created wheel for tinynumpy: filename=tinynumpy-1.2.1-py3-none-any.whl size=18463 sha256=151023c8dbccb717078bb049393c487c1805da73c97b7a2a13d338ab417c6b2a
  Stored in directory: /root/.cache/pip/wheels/d2/3f/7f/041dc24cd71890caaf36ad2b6ba19bd1f351f335698be12b87
Successfully built tinynumpy


<h2>Importing Tiny NumPy<h2>

In [2]:
from tinynumpy import tinynumpy as tnp

<h2>Creating a 1D matrix</h2>

In [10]:
a = tnp.array([1.2, 3.4, 5.6])
b = tnp.array([1.8, 14, 3.6])
a

array([ 1.2,  3.4,  5.6])

<h2>Vector addition</h2>

In [11]:
tnp.add(a,b)

array([ 3.,  17.4,  9.2])

<h2>Vector multiplication

In [12]:
tnp.multiply(a,b)

array([ 2.16,  47.6,  20.16])

<h2>